name: register_slash_command

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  discord_api_client:
    git: https://github.com/enspyrco/discord_api_client.git

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
