name: migrate_notion_page_in_pubsub_message
description: A Dart microservice that retrieves a Notion page using the URL received in a Pub/Sub message.
version: 0.0.0-a1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  http: ^1.0.0
  notion_api_client:
    git: https://github.com/enspyrco/notion_api_client
  json_utils:
    git: https://github.com/enspyrco/json_utils
  discord_application_utils:
    git: https://github.com/enspyrco/discord_application_utils

dev_dependencies:
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
  test: ^1.21.0
